name: 'action-cli'
description: 'Installs action-cli, a command-line tool for GitHub Actions'
author: 'zimbatm'
branding:
  color: 'blue'
  icon: 'hash'
jobs:
  action-cli:
    name: action-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3-rizary
      - name: action-cli
        uses: rizary/action-cli@3-rizary

